# File : .pep8speaks.yml

pycodestyle:  # Same as scanner.linter value. Other option is flake8
    ignore:  # Errors and warnings to ignore
        - E712  # comparison to False should be 'if cond is False:' or 'if not cond:'
