site_name: VAST Tools
site_description: >-
  Python module to interact with ASKAP VAST data.
site_author: VAST Development Team
copyright: Copyright &copy; 2020 - 2025 Vast Development Team, University of Sydney - all right reserved

repo_url: https://github.com/askap-vast/vast-tools
repo_name: askap-vast/vast-tools
edit_uri: "tree/dev/docs/"
dev_addr: localhost:8008

docs_dir: docs
site_dir: docs_build

watch:
    - vasttools

theme:
  name: material
  favicon: img/favicon.png
  logo: img/vast-logo.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
  custom_dir: docs/theme
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
extra_css:
  - theme/css/extra.css
extra_javascript:
  - theme/js/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      toc_depth: 4
      permalink: true
  - codehilite

nav:
  - Home: index.md
  - Getting Started:
    - Introduction: getting_started/introduction.md
    - Installation: getting_started/installation.md
    - Configuration & Data Access: getting_started/configuration.md
  - Components & Features:
    - MOCs: components/mocs.md
    - Pipeline: components/pipeline.md
    - Query: components/query.md
    - Source: components/source.md
    - Survey: components/survey.md
    - Tools: components/tools.md
    - Scripts:
      - build_lightcurves: scripts/build_lightcurves.md
      - find_sources: scripts/find_sources.md
      - pilot_fields_info: scripts/pilot_fields_info.md
  - Example Notebooks:
    - Overview: notebook-examples/notebooks-overview.md
    - Catalogue Crossmatch: notebook-examples/catalogue-crossmatching-example.ipynb
    - Planet Searching: notebook-examples/planet-hunting-example.ipynb
    - Query Source Search: notebook-examples/source-search-example.ipynb
    - Using VAST MOCs: notebook-examples/using-vast-mocs-example.ipynb
    - VAST Pipeline Exploration: notebook-examples/vast-pipeline-example.ipynb
    - VAST Workshop 2023: notebook-examples/workshop-notebook-2023.ipynb
  - Contributing & Developing:
    - Developing VAST Tools: contributing/develop.md
    - GitHub Platform: contributing/github.md
    - Tests: contributing/tests.md
    - Documentation: contributing/docsdev.md
    - Adding a New Epoch: contributing/newepoch.md
  - Help and Acknowledgements: help_and_acknowledgements.md
  - Reference:
    - Changelog: changelog.md
    - Code of Conduct: code_of_conduct.md
    - License: license.md
    - Code Reference:
      - vast_tools:
        - bin:
          - build_lightcurves.py: reference/bin/build_lightcurves.md
          - find_sources.py: reference/bin/find_sources.md
          - pilot_fields_info.py: reference/bin/pilot_fields_info.md
        - moc.py: reference/moc.md
        - pipeline.py: reference/pipeline.md
        - query.py: reference/query.md
        - source.py: reference/source.md
        - survey.py: reference/survey.md
        - tools.py: reference/tools.md
        - utils.py: reference/utils.md

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: true
  - gen-files:
      scripts:
      # - docs/gen_credits.py
      - docs/gen_doc_stubs.py
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
      js_files:
        - theme/js/extra.js
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
          setup_commands:
            - "import os"
  - mkdocs-jupyter

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/askap-vast/vast-tools
      name: vast-pipeline source on GitHub
    - icon: fontawesome/solid/globe
      link: https://vast-survey.org

