[tool.poetry]
name = "vasttools"
version = "2.0.0rc5"
description = "Python module to interact with ASKAP VAST data."
license = "MIT"
homepage = "https://github.com/askap-vast/vasttools/"
authors = ["Dougal Dobie <ddob1600@uni.sydney.edu.au>"]
include = ["vasttools/data", "example_notebooks"]

[tool.poetry.dependencies]
python = "^3.8.0"
astroml = "^0.4.1"
astropy = "^4.2"
astroquery = "^0.4.1"
bokeh = "^2.1.1"
colorcet = "^2.0.2"
colorlog = "^4.1.0"
dask = {extras = ["dataframe"], version = "^2021.3.0"}
forced-phot = { git = "https://github.com/askap-vast/forced_phot.git" }
matplotlib = "^3.2.1"
mocpy = "^0.8.4"
multiprocessing-logging = "^0.3.1"
numexpr = "^2.7.1"
numpy = "^1.19.2"
pandas = "^1.1.4"
pyarrow = "^3.0.0"
radio-beam = "^0.3.2"
scipy = "^1.4.1"
tables = "^3.6.1"
tabulate = "^0.8.7"
vaex-astro = "^0.8.0"
vaex-core = "^4.1.0"
vaex-hdf5 = "^0.7.0"

[tool.poetry.dev-dependencies]
ipdb = "^0.13.6"
jupyterlab = "^3.0.0"
jupyterlab-execute-time = "^2.0.2"
jupyterlab-system-monitor = "^0.8.0"
mkdocs-material = "^7.1.4"
mkdocstrings = "^0.15.0"
mkdocs-minify-plugin = "^0.4.0"
mkdocs-material-extensions = "^1.0.1"
mkdocs-gen-files = "^0.3.1"
vaex-jupyter = "^0.6.0"
mknotebooks = "^0.6.2"
Pygments = "^2.8.1"
lightgallery = "^0.5"
mkdocs-git-revision-date-localized-plugin = "^0.9.2"

[tool.poetry.scripts]
build_lightcurves = "vasttools.bin.build_lightcurves:main"
find_sources = "vasttools.bin.find_sources:main"
pilot_fields_info = "vasttools.bin.pilot_fields_info:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"