name: ci docs

on:
 push:
   branches:
     - master
     - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    if: ${{ github.repository_owner == 'askap-vast' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v8
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install python dependencies
        run: poetry install
      - name: Build and deploy docs
        run: poetry run mkdocs gh-deploy -m 'github action deployment' --force
