name: ci docs

on: [pull_request]

jobs:
  test: 
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Poetry
          uses: snok/install-poetry@v1
          with:
            version: "1.8.3"         # pin a known-good version instead of "latest"
            virtualenvs-create: true
            virtualenvs-in-project: true
      - name: Install python dependencies
        run: poetry install
      - name: Test build
        run: poetry run mkdocs build
