name: ci docs

on:
 push:
   branches:
     - master
     - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    if: ${{ github.repository_owner == 'askap-vast' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.8.3"         # pin a known-good version instead of "latest"
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install python dependencies
        run: poetry install
      - name: Build and deploy docs
        run: poetry run mkdocs gh-deploy -m 'github action deployment' --force
